name = "gravity-duel"
love_files = ["::git-ls-tree::"] # all files tracked by git
default_targets = ["win64", "macos", "appimage"]
build_directory = "builds"

[windows]
[windows.archive_files]
"LICENSE_FOR_BUILD.txt" = "license.txt"

[windows.exe_metadata]
CompanyName = "Personal"
LegalCopyright = "Copyright (C) 2021-2022 thewizardplusplus <thewizardplusplus@yandex.ru>"
FileVersion = "v1.3.2"
FileDescription = "gravity-duel v1.3.2"

[macos]
[macos.app_metadata]
CFBundleIdentifier = "ru.thewizardplusplus.gravity-duel" # should be in reverse-DNS format
CFBundleShortVersionString = "v1.3.2"
NSHumanReadableCopyright = "Copyright (C) 2021-2022 thewizardplusplus <thewizardplusplus@yandex.ru>"
